<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        
        DB::table('countries')->insert(array(
            0 => array('name' => 'Afeganistão', 'register' => 132, 'favtax' => false),
            1 => array('name' => 'África do Sul', 'register' => 7560, 'favtax' => false),
            2 => array('name' => 'Albânia, República da', 'register' => 175, 'favtax' => false),
            3 => array('name' => 'Alemanha', 'register' => 230, 'favtax' => false),
            4 => array('name' => 'Andorra', 'register' => 370, 'favtax' => true),
            5 => array('name' => 'Angola', 'register' => 400, 'favtax' => false),
            6 => array('name' => 'Anguilla', 'register' => 418, 'favtax' => true),
            7 => array('name' => 'Antigua e Barbuda', 'register' => 434, 'favtax' => true),
            8 => array('name' => 'Antilhas Holandesas', 'register' => 477, 'favtax' => true),
            9 => array('name' => 'Arábia Saudita', 'register' => 531, 'favtax' => false),
            10 => array('name' => 'Argélia', 'register' => 590, 'favtax' => false),
            11 => array('name' => 'Argentina', 'register' => 639, 'favtax' => false),
            12 => array('name' => 'Armênia, República da', 'register' => 647, 'favtax' => false),
            13 => array('name' => 'Aruba', 'register' => 655, 'favtax' => false),
            14 => array('name' => 'Austrália', 'register' => 698, 'favtax' => false),
            15 => array('name' => 'Áustria', 'register' => 728, 'favtax' => false),
            16 => array('name' => 'Azerbaijão, República do', 'register' => 736, 'favtax' => false),
            17 => array('name' => 'Bahamas, Ilhas', 'register' => 779, 'favtax' => true),
            18 => array('name' => 'Bahrein, Ilhas', 'register' => 809, 'favtax' => true),
            19 => array('name' => 'Bangladesh', 'register' => 817, 'favtax' => false),
            20 => array('name' => 'Barbados', 'register' => 833, 'favtax' => true),
            21 => array('name' => 'Belarus', 'register' => 850, 'favtax' => false),
            22 => array('name' => 'Bélgica', 'register' => 876, 'favtax' => false),
            23 => array('name' => 'Belize', 'register' => 884, 'favtax' => true),
            24 => array('name' => 'Benin', 'register' => 2291, 'favtax' => false),
            25 => array('name' => 'Bermudas', 'register' => 906, 'favtax' => true),
            26 => array('name' => 'Bolívia', 'register' => 973, 'favtax' => false),
            27 => array('name' => 'Bósnia-Herzegovina', 'register' => 981, 'favtax' => false),
            28 => array('name' => 'Botsuana', 'register' => 1015, 'favtax' => false),
            29 => array('name' => 'Brasil', 'register' => 1058, 'favtax' => false),
            30 => array('name' => 'Brunei', 'register' => 1082, 'favtax' => false),
            31 => array('name' => 'Bulgária, República da', 'register' => 1112, 'favtax' => false),
            32 => array('name' => 'Burkina Faso', 'register' => 310, 'favtax' => false),
            33 => array('name' => 'Burundi', 'register' => 1155, 'favtax' => false),
            34 => array('name' => 'Butão', 'register' => 1198, 'favtax' => false),
            35 => array('name' => 'Cabo Verde, República de', 'register' => 1279, 'favtax' => false),
            36 => array('name' => 'Camarões', 'register' => 1457, 'favtax' => false),
            37 => array('name' => 'Camboja', 'register' => 1414, 'favtax' => false),
            38 => array('name' => 'Canadá', 'register' => 1490, 'favtax' => false),
            39 => array('name' => 'Canal, Ilhas do (Jersey e Guernsey)', 'register' => 1504, 'favtax' => true),
            40 => array('name' => 'Canárias, Ilhas', 'register' => 1511, 'favtax' => false),
            41 => array('name' => 'Catar', 'register' => 1546, 'favtax' => false),
            42 => array('name' => 'Cayman, Ilhas', 'register' => 1376, 'favtax' => true),
            43 => array('name' => 'Cazaquistão, República do', 'register' => 1538, 'favtax' => false),
            44 => array('name' => 'Chade', 'register' => 7889, 'favtax' => false),
            45 => array('name' => 'Chile', 'register' => 1589, 'favtax' => false),
            46 => array('name' => 'China, República Popular da', 'register' => 1600, 'favtax' => false),
            47 => array('name' => 'Chipre', 'register' => 1635, 'favtax' => true),
            48 => array('name' => 'Christmas, Ilha (Navidad)', 'register' => 5118, 'favtax' => false),
            49 => array('name' => 'Cingapura', 'register' => 7412, 'favtax' => false),
            50 => array('name' => 'Cocos (Keeling), Ilhas', 'register' => 1651, 'favtax' => false),
            51 => array('name' => 'Colômbia', 'register' => 1694, 'favtax' => false),
            52 => array('name' => 'Comores, Ilhas', 'register' => 1732, 'favtax' => false),
            53 => array('name' => 'Congo, República Democrática do', 'register' => 8885, 'favtax' => false),
            54 => array('name' => 'Congo, República do', 'register' => 1775, 'favtax' => false),
            55 => array('name' => 'Cook, Ilhas', 'register' => 1830, 'favtax' => true),
            56 => array('name' => 'Coréia, Rep. Pop. Democrática da', 'register' => 1872, 'favtax' => false),
            57 => array('name' => 'Coréia, República da', 'register' => 1902, 'favtax' => false),
            58 => array('name' => 'Costa do Marfim', 'register' => 1937, 'favtax' => false),
            59 => array('name' => 'Costa Rica', 'register' => 1961, 'favtax' => true),
            60 => array('name' => 'Coveite', 'register' => 1988, 'favtax' => false),
            61 => array('name' => 'Croácia, República da', 'register' => 1953, 'favtax' => false),
            62 => array('name' => 'Cuba', 'register' => 1996, 'favtax' => false),
            63 => array('name' => 'Dinamarca', 'register' => 2321, 'favtax' => false),
            64 => array('name' => 'Djibuti', 'register' => 7838, 'favtax' => true),
            65 => array('name' => 'Dominica, Ilha', 'register' => 2356, 'favtax' => true),
            66 => array('name' => 'Egito', 'register' => 2402, 'favtax' => false),
            67 => array('name' => 'El Salvador', 'register' => 6874, 'favtax' => false),
            68 => array('name' => 'Emirados Árabes Unidos', 'register' => 2445, 'favtax' => false),
            69 => array('name' => 'Equador', 'register' => 2399, 'favtax' => false),
            70 => array('name' => 'Eritréia', 'register' => 2437, 'favtax' => false),
            71 => array('name' => 'Escócia', 'register' => 6289, 'favtax' => false),
            72 => array('name' => 'Eslovaca, República', 'register' => 2470, 'favtax' => false),
            73 => array('name' => 'Eslovênia, República da', 'register' => 2461, 'favtax' => false),
            74 => array('name' => 'Espanha', 'register' => 2453, 'favtax' => false),
            75 => array('name' => 'Estados Unidos', 'register' => 2496, 'favtax' => false),
            76 => array('name' => 'Estônia, República da', 'register' => 2518, 'favtax' => false),
            77 => array('name' => 'Etiópia', 'register' => 2534, 'favtax' => false),
            78 => array('name' => 'Falkland (Ilhas Malvinas)', 'register' => 2550, 'favtax' => false),
            79 => array('name' => 'Feroe, Ilhas', 'register' => 2593, 'favtax' => false),
            80 => array('name' => 'Fiji', 'register' => 8702, 'favtax' => false),
            81 => array('name' => 'Filipinas', 'register' => 2674, 'favtax' => false),
            82 => array('name' => 'Finlândia', 'register' => 2712, 'favtax' => false),
            83 => array('name' => 'Formosa (Taiwan)', 'register' => 1619, 'favtax' => false),
            84 => array('name' => 'França', 'register' => 2755, 'favtax' => false),
            85 => array('name' => 'Gabão', 'register' => 2810, 'favtax' => false),
            86 => array('name' => 'Gales, País de', 'register' => 6289, 'favtax' => false),
            87 => array('name' => 'Gâmbia', 'register' => 2852, 'favtax' => false),
            88 => array('name' => 'Gana', 'register' => 2895, 'favtax' => false),
            89 => array('name' => 'Geórgia, República da', 'register' => 2917, 'favtax' => false),
            90 => array('name' => 'Gibraltar', 'register' => 2933, 'favtax' => true),
            91 => array('name' => 'Grã-Bretanha', 'register' => 6289, 'favtax' => false),
            92 => array('name' => 'Granada', 'register' => 2976, 'favtax' => true),
            93 => array('name' => 'Grécia', 'register' => 3018, 'favtax' => false),
            94 => array('name' => 'Groenlândia', 'register' => 3050, 'favtax' => false),
            95 => array('name' => 'Guadalupe', 'register' => 3093, 'favtax' => false),
            96 => array('name' => 'Guam', 'register' => 3131, 'favtax' => false),
            97 => array('name' => 'Guatemala', 'register' => 3174, 'favtax' => false),
            98 => array('name' => 'Guiana', 'register' => 3379, 'favtax' => false),
            99 => array('name' => 'Guiana Francesa', 'register' => 3255, 'favtax' => false),
            100 => array('name' => 'Guiné', 'register' => 3298, 'favtax' => false),
            101 => array('name' => 'Guiné-Bissau', 'register' => 3344, 'favtax' => false),
            102 => array('name' => 'Guiné-Equatorial', 'register' => 3310, 'favtax' => false),
            103 => array('name' => 'Haiti', 'register' => 3417, 'favtax' => false),
            104 => array('name' => 'Holanda (Países Baixos)', 'register' => 5738, 'favtax' => false),
            105 => array('name' => 'Honduras', 'register' => 3450, 'favtax' => false),
            106 => array('name' => 'Hong Kong, Região Adm. Especial', 'register' => 3514, 'favtax' => false),
            107 => array('name' => 'Hungria, República da', 'register' => 3557, 'favtax' => false),
            108 => array('name' => 'Iêmen', 'register' => 3573, 'favtax' => false),
            109 => array('name' => 'Índia', 'register' => 3611, 'favtax' => false),
            110 => array('name' => 'Indonésia', 'register' => 3654, 'favtax' => false),
            111 => array('name' => 'Inglaterra', 'register' => 6289, 'favtax' => false),
            112 => array('name' => 'Irã, República Islâmica do', 'register' => 3727, 'favtax' => false),
            113 => array('name' => 'Iraque', 'register' => 3697, 'favtax' => false),
            114 => array('name' => 'Irlanda', 'register' => 3751, 'favtax' => false),
            115 => array('name' => 'Irlanda do Norte', 'register' => 6289, 'favtax' => false),
            116 => array('name' => 'Islândia', 'register' => 3794, 'favtax' => false),
            117 => array('name' => 'Israel', 'register' => 3832, 'favtax' => false),
            118 => array('name' => 'Itália', 'register' => 3867, 'favtax' => false),
            119 => array('name' => 'Iugoslávia, República Fed. da', 'register' => 3883, 'favtax' => false),
            120 => array('name' => 'Jamaica', 'register' => 3913, 'favtax' => false),
            121 => array('name' => 'Japão', 'register' => 3999, 'favtax' => false),
            122 => array('name' => 'Johnston, Ilhas', 'register' => 3964, 'favtax' => false),
            123 => array('name' => 'Jordânia', 'register' => 4030, 'favtax' => false),
            124 => array('name' => 'Kiribati', 'register' => 4111, 'favtax' => false),
            125 => array('name' => 'Laos, Rep. Pop. Democrática do', 'register' => 4200, 'favtax' => false),
            126 => array('name' => 'Lebuan', 'register' => 4235, 'favtax' => true),
            127 => array('name' => 'Lesoto', 'register' => 4260, 'favtax' => false),
            128 => array('name' => 'Letônia, República da', 'register' => 4278, 'favtax' => false),
            129 => array('name' => 'Líbano', 'register' => 4316, 'favtax' => false),
            130 => array('name' => 'Libéria', 'register' => 4340, 'favtax' => true),
            131 => array('name' => 'Líbia', 'register' => 4383, 'favtax' => false),
            132 => array('name' => 'Liechtenstein', 'register' => 4405, 'favtax' => true),
            133 => array('name' => 'Lituânia, República da', 'register' => 4421, 'favtax' => false),
            134 => array('name' => 'Luxemburgo', 'register' => 4456, 'favtax' => false),
            135 => array('name' => 'Macau', 'register' => 4472, 'favtax' => false),
            136 => array('name' => 'Macedônia', 'register' => 4499, 'favtax' => false),
            137 => array('name' => 'Madagascar', 'register' => 4502, 'favtax' => false),
            138 => array('name' => 'Madeira, Ilha da', 'register' => 4525, 'favtax' => true),
            139 => array('name' => 'Malásia', 'register' => 4553, 'favtax' => false),
            140 => array('name' => 'Malavi', 'register' => 4588, 'favtax' => false),
            141 => array('name' => 'Maldivas', 'register' => 4618, 'favtax' => false),
            142 => array('name' => 'Máli', 'register' => 4642, 'favtax' => false),
            143 => array('name' => 'Malta', 'register' => 4677, 'favtax' => true),
            144 => array('name' => 'Man, Ilhas', 'register' => 3595, 'favtax' => true),
            145 => array('name' => 'Marianas do Norte', 'register' => 4723, 'favtax' => false),
            146 => array('name' => 'Marrocos', 'register' => 4740, 'favtax' => false),
            147 => array('name' => 'Marshall, Ilhas', 'register' => 4766, 'favtax' => true),
            148 => array('name' => 'Martinica', 'register' => 4774, 'favtax' => false),
            149 => array('name' => 'Maurício', 'register' => 4855, 'favtax' => true),
            150 => array('name' => 'Mauritânia', 'register' => 4880, 'favtax' => false),
            151 => array('name' => 'México', 'register' => 4936, 'favtax' => false),
            152 => array('name' => 'Mianmar (Birmânia)', 'register' => 930, 'favtax' => false),
            153 => array('name' => 'Micronésia', 'register' => 4995, 'favtax' => false),
            154 => array('name' => 'Midway, Ilhas', 'register' => 4901, 'favtax' => false),
            155 => array('name' => 'Moçambique', 'register' => 5053, 'favtax' => false),
            156 => array('name' => 'Moldávia, República da', 'register' => 4944, 'favtax' => false),
            157 => array('name' => 'Mônaco', 'register' => 4952, 'favtax' => true),
            158 => array('name' => 'Mongólia', 'register' => 4979, 'favtax' => false),
            159 => array('name' => 'Montserrat, Ilhas', 'register' => 5010, 'favtax' => true),
            160 => array('name' => 'Namíbia', 'register' => 5070, 'favtax' => false),
            161 => array('name' => 'Nauru', 'register' => 5088, 'favtax' => true),
            162 => array('name' => 'Nepal', 'register' => 5177, 'favtax' => false),
            163 => array('name' => 'Nicarágua', 'register' => 5215, 'favtax' => false),
            164 => array('name' => 'Niger', 'register' => 5258, 'favtax' => false),
            165 => array('name' => 'Nigéria', 'register' => 5282, 'favtax' => false),
            166 => array('name' => 'Niue, Ilha', 'register' => 5312, 'favtax' => true),
            167 => array('name' => 'Norfolk, Ilha', 'register' => 5355, 'favtax' => false),
            168 => array('name' => 'Noruega', 'register' => 5380, 'favtax' => false),
            169 => array('name' => 'Nova Caledônia', 'register' => 5428, 'favtax' => false),
            170 => array('name' => 'Nova Zelândia', 'register' => 5487, 'favtax' => false),
            171 => array('name' => 'Omã', 'register' => 5568, 'favtax' => false),
            172 => array('name' => 'Países Baixos (Holanda)', 'register' => 5738, 'favtax' => false),
            173 => array('name' => 'Palau', 'register' => 5754, 'favtax' => false),
            174 => array('name' => 'Panamá', 'register' => 5800, 'favtax' => true),
            175 => array('name' => 'Papua Nova Guiné', 'register' => 5452, 'favtax' => false),
            176 => array('name' => 'Paquistão', 'register' => 5762, 'favtax' => false),
            177 => array('name' => 'Paraguai', 'register' => 5860, 'favtax' => false),
            178 => array('name' => 'Peru', 'register' => 5894, 'favtax' => false),
            179 => array('name' => 'Pitcairn, Ilha', 'register' => 5932, 'favtax' => false),
            180 => array('name' => 'Polinésia Francesa', 'register' => 5991, 'favtax' => false),
            181 => array('name' => 'Polônia, República da', 'register' => 6033, 'favtax' => false),
            182 => array('name' => 'Porto Rico', 'register' => 6114, 'favtax' => false),
            183 => array('name' => 'Portugal', 'register' => 6076, 'favtax' => false),
            184 => array('name' => 'Quênia', 'register' => 6238, 'favtax' => false),
            185 => array('name' => 'Quirguiz, República', 'register' => 6254, 'favtax' => false),
            186 => array('name' => 'Reino Unido', 'register' => 6289, 'favtax' => false),
            187 => array('name' => 'República Centro-Africana', 'register' => 6408, 'favtax' => false),
            188 => array('name' => 'República Dominicana', 'register' => 6475, 'favtax' => false),
            189 => array('name' => 'Reunião, Ilha', 'register' => 6602, 'favtax' => false),
            190 => array('name' => 'Romênia', 'register' => 6700, 'favtax' => false),
            191 => array('name' => 'Ruanda', 'register' => 6750, 'favtax' => false),
            192 => array('name' => 'Rússia', 'register' => 6769, 'favtax' => false),
            193 => array('name' => 'Saara Ocidental', 'register' => 6858, 'favtax' => false),
            194 => array('name' => 'Salomão, Ilhas', 'register' => 6777, 'favtax' => false),
            195 => array('name' => 'Samoa', 'register' => 6904, 'favtax' => true),
            196 => array('name' => 'Samoa Americana', 'register' => 6912, 'favtax' => false),
            197 => array('name' => 'San Marino', 'register' => 6971, 'favtax' => true),
            198 => array('name' => 'Santa Helena', 'register' => 7102, 'favtax' => false),
            199 => array('name' => 'Santa Lúcia', 'register' => 7153, 'favtax' => true),
            200 => array('name' => 'São Cristóvão e Neves', 'register' => 6955, 'favtax' => true),
            201 => array('name' => 'São Pedro e Miquelon', 'register' => 7005, 'favtax' => false),
            202 => array('name' => 'São Tomé e Príncipe, Ilhas', 'register' => 7200, 'favtax' => false),
            203 => array('name' => 'São Vicente e Granadinas', 'register' => 7056, 'favtax' => true),
            204 => array('name' => 'Senegal', 'register' => 7285, 'favtax' => false),
            205 => array('name' => 'Serra Leoa', 'register' => 7358, 'favtax' => false),
            206 => array('name' => 'Seychelles', 'register' => 7315, 'favtax' => true),
            207 => array('name' => 'Síria, República Árabe da', 'register' => 7447, 'favtax' => false),
            208 => array('name' => 'Somália', 'register' => 7480, 'favtax' => false),
            209 => array('name' => 'Sri Lanka', 'register' => 7501, 'favtax' => false),
            210 => array('name' => 'Suazilândia', 'register' => 7544, 'favtax' => false),
            211 => array('name' => 'Sudão', 'register' => 7595, 'favtax' => false),
            212 => array('name' => 'Suécia', 'register' => 7641, 'favtax' => false),
            213 => array('name' => 'Suíça', 'register' => 7676, 'favtax' => false),
            214 => array('name' => 'Suriname', 'register' => 7706, 'favtax' => false),
            215 => array('name' => 'Tadjiquistão', 'register' => 7722, 'favtax' => false),
            216 => array('name' => 'Tailândia', 'register' => 7765, 'favtax' => false),
            217 => array('name' => 'Tanzânia, República Unida da', 'register' => 7803, 'favtax' => false),
            218 => array('name' => 'Tcheca, República', 'register' => 7919, 'favtax' => false),
            219 => array('name' => 'Território Britânico Oc. Índico', 'register' => 7820, 'favtax' => false),
            220 => array('name' => 'Timor Leste', 'register' => 7951, 'favtax' => false),
            221 => array('name' => 'Togo', 'register' => 8001, 'favtax' => false),
            222 => array('name' => 'Tonga', 'register' => 8109, 'favtax' => true),
            223 => array('name' => 'Toquelau, Ilhas', 'register' => 8052, 'favtax' => false),
            224 => array('name' => 'Trinidad e Tobago', 'register' => 8150, 'favtax' => false),
            225 => array('name' => 'Tunísia', 'register' => 8206, 'favtax' => false),
            226 => array('name' => 'Turcas e Caicos, Ilhas', 'register' => 8230, 'favtax' => true),
            227 => array('name' => 'Turcomenistão, República do', 'register' => 8249, 'favtax' => false),
            228 => array('name' => 'Turquia', 'register' => 8273, 'favtax' => false),
            229 => array('name' => 'Tuvalu', 'register' => 8281, 'favtax' => false),
            230 => array('name' => 'Ucrânia', 'register' => 8311, 'favtax' => false),
            231 => array('name' => 'Uganda', 'register' => 8338, 'favtax' => false),
            232 => array('name' => 'Uruguai', 'register' => 8451, 'favtax' => false),
            233 => array('name' => 'Uzbequistão, República do', 'register' => 8478, 'favtax' => false),
            234 => array('name' => 'Vanuatu', 'register' => 5517, 'favtax' => true),
            235 => array('name' => 'Vaticano, Estado da Cidade do', 'register' => 8486, 'favtax' => false),
            236 => array('name' => 'Venezuela', 'register' => 8508, 'favtax' => false),
            237 => array('name' => 'Vietnã', 'register' => 8583, 'favtax' => false),
            238 => array('name' => 'Virgens, Ilhas (Britânicas)', 'register' => 8630, 'favtax' => true),
            239 => array('name' => 'Virgens, Ilhas (E.U.A.)', 'register' => 8664, 'favtax' => true),
            240 => array('name' => 'Wake, Ilha', 'register' => 8737, 'favtax' => false),
            241 => array('name' => 'Wallis e Futuna, Ilhas', 'register' => 8753, 'favtax' => false),
            242 => array('name' => 'Zâmbia', 'register' => 8907, 'favtax' => false),
            243 => array('name' => 'Zimbábue', 'register' => 6653, 'favtax' => false),
            244 => array('name' => 'Zona do Canal do Panamá', 'register' => 8958, 'favtax' => false),

        ));
    }
}
